"""Build docs/tools/ from tools.yml.

Copies each fetched tool's docs folder into docs/tools/<name>/ and writes the
Tools sidebar (docs/tools/.nav.yml) and overview table (docs/tools/index.md).
"""

import shutil
import subprocess
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
CACHE = ROOT / ".cache" / "repos"
TOOLS_DIR = ROOT / "docs" / "tools"


def fetch(tool):
    name, repo, ref, path = tool["name"], tool["repo"], tool["ref"], tool["path"]
    clone = CACHE / name
    shutil.rmtree(clone, ignore_errors=True)
    subprocess.run(
        ["git", "clone", "--quiet", "--depth", "1", "--branch", ref,
         f"https://github.com/{repo}.git", str(clone)],
        check=True,
    )
    source = clone / path
    if not source.is_dir() or source.is_symlink():
        sys.exit(f"{repo}@{ref} has no '{path}' folder")
    # Symlinks could pull files from outside the repo into the public site.
    links = [p for p in source.rglob("*") if p.is_symlink()]
    if links:
        sys.exit(f"{repo}@{ref}: symlinks are not allowed in docs: "
                 + ", ".join(str(p.relative_to(clone)) for p in links))
    target = TOOLS_DIR / name
    shutil.rmtree(target, ignore_errors=True)
    shutil.copytree(source, target, symlinks=True)
    print(f"{name}: {repo}@{ref}/{path} -> {target.relative_to(ROOT)}")


def write_nav(tools):
    nav = [{"Overview": "index.md"}]
    for tool in tools:
        if "links" in tool:
            nav.append({tool["title"]: tool["links"]})
        else:
            nav.append(tool["name"])
    text = yaml.safe_dump({"title": "Tools", "nav": nav},
                          sort_keys=False, allow_unicode=True)
    (TOOLS_DIR / ".nav.yml").write_text("# Generated by scripts/fetch_tools.py from tools.yml\n" + text)


def write_index(tools):
    rows = []
    for tool in tools:
        if "links" in tool:
            first = next(iter(tool["links"][0].values()))
            docs = f"[{tool['title']}]({first})"
        else:
            docs = f"[{tool['title']}]({tool['name']}/index.md)"
        rows.append(f"| {tool['title']} | {tool['description']} | {docs} |")
    (TOOLS_DIR / "index.md").write_text(
        "<!-- Generated by scripts/fetch_tools.py from tools.yml -->\n\n"
        "# Tools\n\n"
        "| Tool | Description | Documentation |\n"
        "|---|---|---|\n"
        + "\n".join(rows) + "\n\n"
        "Descriptions are taken from each repository's GitHub description.\n\n"
        "To add a tool, follow the [tool docs template](../contributing/tool-docs-template.md).\n"
    )


def main():
    tools = yaml.safe_load((ROOT / "tools.yml").read_text())["tools"]
    TOOLS_DIR.mkdir(parents=True, exist_ok=True)
    fetched = {t["name"] for t in tools if "links" not in t}
    # Remove folders of tools that are no longer listed.
    for old in TOOLS_DIR.iterdir():
        if old.is_dir() and old.name not in fetched:
            shutil.rmtree(old)
    for tool in tools:
        if "links" not in tool:
            fetch(tool)
    write_nav(tools)
    write_index(tools)


if __name__ == "__main__":
    main()
